Fixes issue #65
tripal/tripal_jbrowse pull request #66
Opened 2022-01-27 20:21 UTC by reynoldtan

This PR fixes Issue #65 - Unable to modify instance.

The error is caused by hook_validate when modifying an instance where there is another instance and both share the same organism. This fix takes into account sequence assembly information before checking for identical instance.

2022-01-28 01:44 UTC, dsenalik commented
There is a pull request that is a fix for your tests failing, see

https://github.com/tripal/tripal/issues/1237

2022-02-03 20:56 UTC, laceysanderson requested changes
✅  Code looks good

The validation is good too and testing worked as expected :-) 

Only one thing to fix. Right now it disables the analysis form field on edit even it is not yet. Admin should be able to go back and add analysis after the initial creation. This is common if the first time they didn't bother because it was the only assembly or the functionality didn't exist yet, but now there are many assemblies and they want to make it more clear.

2022-02-08 21:11 UTC, reynoldtan commented
The latest commit fixes the issue of field sequence assembly set to disabled by default, and as part of the fix, it will now save value set to this field when saving modifications.

Please note that with this fix, the edit form will only allow modification of sequence assembly when it was not set previously in create/add form.

To test:
1. Create an instance and leave sequence assembly field empty.
2. Modify this instance, and set a value for sequence assembly field.
3. Click save. Validation rules in the previous commit still apply.

2022-02-22 22:03 UTC, laceysanderson approved these changes
Looks good and works perfectly -Thank you @reynoldtan

2022-02-22 22:03 UTC, merged